# Generated by Django 5.0.2 on 2024-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('clave_AWS', models.CharField(max_length=100, null=True)),
                ('valor_AWS', models.CharField(max_length=100, null=True)),
                ('clave_IBM', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'deployment',
            },
        ),
    ]
