# Generated by Django 5.0.2 on 2024-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='clave_AWS',
            new_name='private_AWS',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='clave_IBM',
            new_name='public_AWS',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='valor_AWS',
            new_name='s3_AWS',
        ),
        migrations.AddField(
            model_name='deployment',
            name='token_IBM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
