# Generated by Django 5.0.2 on 2024-02-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='link',
            table='link',
        ),
    ]
