# Generated by Django 5.0.2 on 2024-02-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
    ]
