# Generated by Django 5.0.2 on 2024-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_remove_link_created_at_remove_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cadena',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
