# Generated by Django 5.0.2 on 2024-04-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_link_cadena'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
