# Generated by Django 5.0.2 on 2024-04-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_link_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='nombre',
        ),
    ]
