# Generated by Django 5.0.2 on 2024-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_remove_link_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_desplegada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
