# Generated by Django 5.0.2 on 2024-06-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_remove_link_url_desplegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
