# Generated by Django 5.0.2 on 2024-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_alter_link_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
