# Generated by Django 5.0.2 on 2024-03-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link', '0004_link_cadena'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.link')),
            ],
            options={
                'db_table': 'circuitIdentity',
            },
        ),
    ]
