# Generated by Django 5.0.2 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitidentity',
            name='link',
        ),
        migrations.AddField(
            model_name='circuitidentity',
            name='link_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
