# Generated by Django 5.0.2 on 2024-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0002_remove_circuitidentity_link_circuitidentity_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitidentity',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
