# Generated by Django 5.0.2 on 2024-04-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0004_circuitidentity_circuito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitidentity',
            old_name='circuito',
            new_name='codigo_circuito',
        ),
    ]
