# Generated by Django 5.0.2 on 2024-04-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0005_rename_circuito_circuitidentity_codigo_circuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitidentity',
            name='codigo_circuito',
        ),
    ]
