# Generated by Django 5.0.2 on 2024-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0006_remove_circuitidentity_codigo_circuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitidentity',
            name='link_id',
            field=models.IntegerField(unique=True),
        ),
    ]
