# Generated by Django 5.0.2 on 2024-05-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0007_alter_circuitidentity_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitidentity',
            name='url_desplegada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
